blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/webrix-ai/plugin-marketplace-wizard/discussions
    about: Ask questions and discuss with other users in GitHub Discussions.
