name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [20, 22]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      # - name: Format check
      #   if: matrix.os == 'ubuntu-latest' && matrix.node-version == 22
      #   run: pnpm format:check

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
